name       : mtxclient
version    : 0.9.1
release    : 4
source     :
    - https://github.com/Nheko-Reborn/mtxclient/archive/refs/tags/v0.9.1.tar.gz : bae82daa019ecdedb2433177b3d973b72f337d14e7a4f480a490559235391005
license    : MIT
homepage   : https://nheko-reborn.github.io/
component  : network.im
summary    : Client API library for Matrix
description: |
    Client API library for Matrix
builddeps  :
    - pkgconfig(coeurl)
    - pkgconfig(libcrypto)
    - pkgconfig(libcurl)
    - pkgconfig(libevent_core)
    - pkgconfig(libsodium)
    - pkgconfig(nlohmann_json)
    - pkgconfig(olm)
    - pkgconfig(re2)
    - pkgconfig(spdlog)
clang      : yes
setup      : |
    %cmake_ninja -DBUILD_LIB_TESTS=false
build      : |
    %ninja_build
install    : |
    %ninja_install
